### ISSUE TITLE
Export tasks as csv broken

### ISSUE THREAD

**Issue by rahensonzam** [nextgensparx/zra-helper#116] opened 2019-04-04 09:19 UTC
**Version**
v1.4.0-beta.2

**Describe the bug**
Export tasks as `csv` is not workng as expected
With "Only export client tasks" off it acts as if it's on.
✔,Client1
✔,Client2
With "Only export client tasks" on it only shows the root task.
✔,Run actions on clients

**To Reproduce**
1. Do a run.
2. Export tasks as `csv`, with & without "Only export client tasks"
3. Check export

**Expected behavior**
Expected it to match export as text, just in `csv` format.

**Comment by siphomateke** [comment] 2019-04-04 09:25
The reason it's like this is because I wasn't sure how to indicate that a task is the child of another one. 

@rahensonzam Could you please update the issue to give an example (in the expected behavior section) of how you would like the CSV export to look?

**Comment by siphomateke** [comment] 2019-04-28 14:46
Since no better way to display the data in CSV format was suggested, I'm closing this issue.

**Closed as completed by siphomateke** 2019-04-28 14:46 UTC
Labels: bug, question, wontfix
